name: Build and package VSCode extension

on:
    push:
        branches:
            - main
    pull_request: # Added pull_request event
        branches:
            - main
    workflow_dispatch:

jobs:
    extension:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - name: Install Yarn
              run: |
                  npm install -g yarn
            - name: Build extension
              run: |
                  yarn install
                  yarn run prettier-check
                  yarn run type-check
                  yarn run compile
                  yarn run lint

            - name: Package extension
              run: |
                  npx @vscode/vsce package

            - name: Upload VSIX as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: vsix
                  path: '*.vsix'